import yaml

from dnslib import NS, SOA, TXT

from .record import Record

RECORD_TYPE = {
    'NS': NS,
    'SOA': SOA,
    'TXT': TXT
}

class Config:
    def __init__(self, config_file="/etc/padawanv6/config.yml"):
        with open(config_file, 'r') as ymlfile:
            cfg = yaml.load(ymlfile)

        self.DIGIT_TAG = "%DIGITS%"
        self.record_pattern = cfg['record_pattern']
        self.ipv6_subnet = cfg['ipv6_subnet']
        self.records = {
            'ok': [
                Record(TXT, 'Generated by PadawanV6')
            ],
            'ko': [
                Record(TXT, 'PadawanV6 respond only to IPv6 PTR request'),
                Record(TXT, 'PadawanV6 respond only to \'' + self.ipv6_subnet + '\' zone')
            ] + [Record(RECORD_TYPE[record['type']], record['value']) for record in cfg['records']]
        }
